[package]
name = "ggetris"
version = "0.1.0"
authors = ["chinatsu <lolexplode@gmail.com>"]
edition = "2018"

[dependencies]
ggez = "0.5.1"
rand = "0.7"
lazy_static = "1.4.0"
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }
