[input]
left = "left"
right = "right"
down = "down"
harddrop = "space"
rotate_cw = "z"
rotate_ccw = "x"
flip = "c"
restart = "t"
switch = "l"

[game]
das = 5 # represents the number of frames at 60fps
